import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { activationBuildIdentityModule } from './activation-build-identity.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const output = path.join(root, 'dist');
const intakeBuildEnabled = process.env.ARC_BUILD_INTAKE_ENABLED === 'true';
const analyticsBuildEnabled = process.env.ARC_BUILD_ANALYTICS_ENABLED === 'true';
const intakeBuildMarkerPath = path.join(root, 'netlify/lib/intake-build-marker.mjs');
const activationBuildIdentityPath = path.join(root, 'netlify/lib/activation-build-identity.mjs');
const publicEntries = Object.freeze([
  'index.html',
  'favicon.svg',
  'robots.txt',
  'sitemap.xml',
  'assets',
  'thank-you',
  'payment-success',
  'review',
  'claim',
  'privacy',
  'terms',
  'refunds',
  'service-scope',
  'support',
]);

await writeFile(intakeBuildMarkerPath, `// Generated by scripts/build-site.mjs from the build-scoped intake switch and
// bundled into the same deploy's Functions. The committed/default marker is
// deliberately closed.
export const INTAKE_BUILD_MARKER = Object.freeze({
  schema: 'arc-intake-build-marker-v1',
  version: 1,
  intake_enabled: ${intakeBuildEnabled},
});
`);

// COMMIT_REF exists in Netlify's build environment, but is not a dependable
// Functions runtime variable. Capture it once and bundle the immutable identity.
// Local builds without COMMIT_REF deliberately produce a closed identity.
await writeFile(activationBuildIdentityPath, activationBuildIdentityModule(process.env.COMMIT_REF));

await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
for (const entry of publicEntries) {
  await cp(path.join(root, entry), path.join(output, entry), { recursive: true, errorOnExist: true });
}

if (!analyticsBuildEnabled) {
  for (const relative of ['index.html', 'thank-you/index.html']) {
    const file = path.join(output, relative);
    const source = await readFile(file, 'utf8');
    const closed = source.replace('data-analytics-build-enabled="true"', 'data-analytics-build-enabled="false"');
    if (closed === source || !/data-analytics-build-enabled="false"/.test(closed)) {
      throw new Error(`Analytics could not be compiled fail-closed: ${relative}`);
    }
    await writeFile(file, closed);
  }
}

if (!intakeBuildEnabled) {
  // Production intake is deliberately compiled closed. Keeping the form fields
  // in source supports local QA, but the default deploy must not expose a POST.
  // Even an explicitly enabled build submits only through the runtime-gated
  // Function; native Netlify Forms registration is never deployed.
  const builtHomePath = path.join(output, 'index.html');
  const builtHome = await readFile(builtHomePath, 'utf8');
  const closedHome = builtHome
    .replace(' data-intake-build-enabled="true"', ' data-intake-build-enabled="false"')
    .replace(' action="/api/intake/submit"', ' action="/"')
    .replace(' enctype="multipart/form-data"', '')
    .replace(' method="POST" name="arc-preview"', ' name="arc-preview"');
  if (closedHome === builtHome || !/data-intake-build-enabled="false"/.test(closedHome) ||
      /data-netlify=|name="form-name"|netlify-honeypot=|method="POST"/.test(closedHome) ||
      /<form\b[^>]*action="\/api\/intake\/submit"/.test(closedHome)) {
    throw new Error('Production intake could not be compiled fail-closed.');
  }
  await writeFile(builtHomePath, closedHome);
}

const built = (await readdir(output)).sort();
if (JSON.stringify(built) !== JSON.stringify([...publicEntries].sort())) {
  throw new Error(`Unexpected deploy output: ${built.join(', ')}`);
}
console.log(`ARC public build created with ${built.length} allowlisted root entries.`);
